version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Toronto"

    allow:
      - dependency-type: "all"

    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"

    assignees:
      - "thedaviddias"

    labels:
      - "dependencies"
      - "dependabot"
