name: 'Init'

runs:
  using: 'composite'
  steps:
    - name: 'setup pnpm'
      id: pnpm-setup
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7

    - name: 'install Node'
      id: node-setup
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version: 16

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
